//Items
export const cards = [
    {
        id: 1,
        img: "./img/Project/project1.jpg",
        projectName: "Tastebite",
        projectDemo: "https://my-landing-pages-1.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Tastebite",
    },
    {
        id: 2,
        img: "./img/Project/project2.jpg",
        projectName: "Uvodo",
        projectDemo: "https://my-landing-pages-2.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Uvodo",
    },
    {
        id: 3,
        img: "./img/Project/project3.jpg",
        projectName: "Car-care-auto-mobile",
        projectDemo: "https://my-landing-pages-3.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Car-care-auto-mobile",
    },
    {
        id: 4,
        img: "./img/Project/project4.jpg",
        projectName: "Car-repair",
        projectDemo: "https://my-landing-pages-4.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Car-repair",
    },
    {
        id: 5,
        img: "./img/Project/project5.jpg",
        projectName: "Clouds",
        projectDemo: "https://my-landing-pages-5.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Clouds",
    },
    {
        id: 6,
        img: "./img/Project/project6.jpg",
        projectName: "Eat-restaurant",
        projectDemo: "https://my-landing-pages-6.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Eat-restaurant",
    },
    {
        id: 7,
        img: "./img/Project/project7.jpg",
        projectName: "Enlive-corporate",
        projectDemo: "https://my-landing-pages-7.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Enlive-corporate",
    },
    {
        id: 8,
        img: "./img/Project/project8.jpg",
        projectName: "Foodz-mobile-app",
        projectDemo: "https://my-landing-pages-8.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Foodz-mobile-app",
    },
    {
        id: 9,
        img: "./img/Project/project9.jpg",
        projectName: "Frames-corporate",
        projectDemo: "https://my-landing-pages-9.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Frames-corporate",
    },
    {
        id: 10,
        img: "./img/Project/project10.jpg",
        projectName: "Getdoctor",
        projectDemo: "https://my-landing-pages-10.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Getdoctor",
    },
    {
        id: 11,
        img: "./img/Project/project11.jpg",
        projectName: "Golden-hotel",
        projectDemo: "https://my-landing-pages-11.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Golden-hotel",
    },
    {
        id: 12,
        img: "./img/Project/project12.jpg",
        projectName: "Grand",
        projectDemo: "https://my-landing-pages-12.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Grand",
    },
    {
        id: 13,
        img: "./img/Project/project13.jpg",
        projectName: "Green-corp-flat",
        projectDemo: "https://my-landing-pages-13.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Green-corp-flat",
    },
    {
        id: 14,
        img: "./img/Project/project14.jpg",
        projectName: "Idata-hosting",
        projectDemo: "https://my-landing-pages-14.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Idata-hosting",
    },
    {
        id: 15,
        img: "./img/Project/project15.jpg",
        projectName: "Ideal-interior-design",
        projectDemo: "https://my-landing-pages-15.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Ideal-interior-design",
    },
    {
        id: 16,
        img: "./img/Project/project16.jpg",
        projectName: "Line",
        projectDemo: "https://my-landing-pages-16.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Line",
    },
    {
        id: 17,
        img: "./img/Project/project17.jpg",
        projectName: "Lovely-wedding",
        projectDemo: "https://my-landing-pages-17.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Lovely-wedding",
    },
    {
        id: 18,
        img: "./img/Project/project18.jpg",
        projectName: "Medplus-medical",
        projectDemo: "https://my-landing-pages-18.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Medplus-medical",
    },
    {
        id: 19,
        img: "./img/Project/project19.jpg",
        projectName: "Midway",
        projectDemo: "https://my-landing-pages-19.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Midway",
    },
    {
        id: 20,
        img: "./img/Project/project20.jpg",
        projectName: "Real-estate-my-home",
        projectDemo: "https://my-landing-pages-20.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Real-estate-my-home",
    },
    {
        id: 21,
        img: "./img/Project/project21.jpg",
        projectName: "Relax-interior",
        projectDemo: "https://my-landing-pages-21.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Relax-interior",
    },
    {
        id: 22,
        img: "./img/Project/project22.jpg",
        projectName: "Restaurant-treehut",
        projectDemo: "https://my-landing-pages-22.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Restaurant-treehut",
    },
    {
        id: 23,
        img: "./img/Project/project23.jpg",
        projectName: "Rocket",
        projectDemo: "https://my-landing-pages-23.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Rocket",
    },
    {
        id: 24,
        img: "./img/Project/project24.jpg",
        projectName: "Rockline-business",
        projectDemo: "https://my-landing-pages-24.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Rockline-business",
    },
    {
        id: 25,
        img: "./img/Project/project25.jpg",
        projectName: "Skytouch",
        projectDemo: "https://my-landing-pages-25.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Skytouch",
    },
    {
        id: 26,
        img: "./img/Project/project26.jpg",
        projectName: "Webtrends",
        projectDemo: "https://my-landing-pages-26.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Webtrends",
    },
    {
        id: 27,
        img: "./img/Project/project27.jpg",
        projectName: "Victory-educational-institution",
        projectDemo: "https://my-landing-pages-27.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Victory-educational-institution",
    },
    {
        id: 28,
        img: "./img/Project/project28.jpg",
        projectName: "Vibrant-corporate",
        projectDemo: "https://my-landing-pages-28.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Vibrant-corporate",
    },
    {
        id: 29,
        img: "./img/Project/project29.jpg",
        projectName: "Vibe",
        projectDemo: "https://my-landing-pages-29.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Vibe",
    },
    {
        id: 30,
        img: "./img/Project/project30.jpg",
        projectName: "Unique",
        projectDemo: "https://my-landing-pages-30.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Unique",
    },
    {
        id: 31,
        img: "./img/Project/project31.jpg",
        projectName: "Trendy",
        projectDemo: "https://my-landing-pages-31.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Trendy",
    },
    {
        id: 32,
        img: "./img/Project/project32.jpg",
        projectName: "Traveller",
        projectDemo: "https://my-landing-pages-32.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Traveller",
    },
    {
        id: 33,
        img: "./img/Project/project33.jpg",
        projectName: "Times-corporate",
        projectDemo: "https://my-landing-pages-33.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Times-corporate",
    },
    {
        id: 34,
        img: "./img/Project/project34.jpg",
        projectName: "Themer",
        projectDemo: "https://my-landing-pages-34.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Themer",
    },
    {
        id: 35,
        img: "./img/Project/project35.jpg",
        projectName: "The-best-wedding",
        projectDemo: "https://my-landing-pages-35.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/The-best-wedding",
    },
    {
        id: 36,
        img: "./img/Project/project36.jpg",
        projectName: "Techking",
        projectDemo: "https://my-landing-pages-36.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Techking",
    },
    {
        id: 37,
        img: "./img/Project/project37.jpg",
        projectName: "Team-business-flat",
        projectDemo: "https://my-landing-pages-37.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Team-business-flat",
    },
    {
        id: 38,
        img: "./img/Project/project38.jpg",
        projectName: "Speed-hosting",
        projectDemo: "https://my-landing-pages-38.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Speed-hosting",
    },
    {
        id: 39,
        img: "./img/Project/project39.jpg",
        projectName: "Smartapp",
        projectDemo: "https://my-landing-pages-39.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Smartapp",
    },
    {
        id: 40,
        img: "./img/Project/project40.jpg",
        projectName: "Smart-interior-designs",
        projectDemo: "https://my-landing-pages-40.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-Landing-Pages/tree/main/Smart-interior-designs",
    },
];